# Generated by Django 5.2 on 2025-05-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='tags',
        ),
    ]
