# Generated by Django 5.2 on 2025-05-15 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_like_blog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together=set(),
        ),
    ]
