# Generated by Django 5.2 on 2025-05-15 12:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_alter_blogview_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together={('user', 'blog')},
        ),
    ]
